### ISSUE TITLE
misc todos for Jan

### ISSUE THREAD

**Issue by BarkleyBG** [BarkleyBG/LCC#86]
(Meeting prep for Monday)

- [x] doc name (#73)
- [x] Review chapters 
    - [x] Chp 0 (#62)
    - [x] Chp 1 (#79) (merged, not reviewed)
    - [x] Chp 2 (#83)
    - [x] Determine whether to add installation stuff in appendix (#84)
- [x] Sketch outline for upcoming / February
    - Split milestones up from alpha/beta? into January/February/beta?
- [x] Walk through outstanding PR's and issues
- [x] How silly is `release` branch? (#57)

**Comment by BarkleyBG** [comment]
I went ahead and marked all these todo's as Alpha version, because I think they should all be taken care of rather soon.

We may split into more than two milestones (alpha/beta).

**Comment by BarkleyBG** [comment]
## doc name

- Add to title page: "With support from Scott, Dave, (Matt?)"

**Comment by BarkleyBG** [comment]
## highlighting
- move forward with changing `\code{}` to `\lstinline{}`
   - Can we nickname `\lstinline{}` to something shorter?
- you can break lines with `\lstinline{foofoo}\allowbreak{}\lstinline{barbarbarbarbar}`

**Comment by BarkleyBG** [comment]
## Chapter 0

- (merge in develop and then) PR it so dave can have appendix
- be careful about VPN language
  - reference chapter 3
  - Acknowledge heuristics
- Add the #84 and more 'recomneded terminals' to Appendix

## Chapter Longleaf
- PR it so it doesn't get too stale?

**Comment by BarkleyBG** [comment]
## Chp 2

- Access CLI on Windows: Mention that we kind of cover these topics elsewhere, too
- Important information must not be stashed in the appendix
- We will (later) add info on on how to install/use RStudio + Emacs (rather than SSH GUI) for unix-ecosystem commands to appendix 
- Let's pre-emptively add "Back to Chapter 0" etc at the end of Chap 2, etc. Link between them nicely since people will probalby be jumping around

### Chp 2 questions for Brian
- Split chapter into 2 pieces? 
    1. Commands (e.g. `ls`, `pwd`, `tree`)
    2. Shell programming (e.g. pipes, filename substitution, etc). 
- Yes, use Chapter 2a and 2b

**Comment by BarkleyBG** [comment]
# Big todo's
- Deliverables before Feb 26th meeting

**Comment by BarkleyBG** [comment]
## Chapter 4-6
- Remove "R" from the title. Python, julia, etc.

### stuff we need to talk about:
- Console / editor
- SFTP and SSH GUI's
- Some SLURM commands
   - Use a "two-pass" idea. Solve issues immediately here.
   - Refer to details in Chapter 5: SLURM?
- 

## Chapter 5: SLURM
- Use a "two-pass" idea,
     - Solve issues immediately (in other chapters) but link to chapter SLURM for in-depth discussion
- Go into more detail about tasks and schedulers here

**Comment by BarkleyBG** [comment]
Should we increase the version? #73

**Comment by BarkleyBG** [comment]
make new milestones for new versions

**Comment by BarkleyBG** [comment]
I've migrated these to other issues, so I'm checking the last box and marking this as closed. yay!
